name: classmates
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+10

environment:
  sdk: ^3.12.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.0
  firebase_core: ^4.12.1
  cloud_firestore: ^6.7.1
  firebase_auth: ^6.5.6
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/homeimage.png
    - assets/mailicon.webp
    - assets/googleIcon.svg.webp
    - assets/1_icon.png
    - assets/2_icon.png
    - assets/3_icon.png
    - assets/4_icon.png
    - assets/postIcon.png
    - assets/Messageiconfinal.png
    - assets/ExperienceIcon.png
    - assets/resorcessIcon.png
    - assets/profileIcon.png
    - assets/HomeIcon.png
    - assets/Experiences_Active.png
    - assets/Resources_Active.png
    - assets/Profile_Active.png
    - assets/Home_active.png
    - assets/settingIcons/
